#!/usr/bin/env python3

import argparse

import commonl


parser = argparse.ArgumentParser(description='static site builder')

# Add the arguments
parser.add_argument('test',
                    metavar='test',
                    type=str,
                    help='the test')

args = parser.parse_args()

print(args.test)
 
